# Project information
docs_dir: docs
site_name: Wanna Be Polymath
site_url: https://wannabepolymath.github.io/
site_author: kivsean
site_description: >-
  a mix of a personal website, portfolio, blog, and more? about everything?

# Repository
repo_name: Sh4peSh1fter/wannabepolymath
repo_url: https://github.com/Sh4peSh1fter/wannabepolymath

# Copyright
copyright: Copyright &copy; 2024 Kivsean

theme:
  name: material
  features:
    # navigation
    - navigation.instant # internal links will be intercepted and dispatched via XHR without fully reloading the page.
    - navigation.instant.progress # progress indicator.
    - navigation.tabs # top-level sections are rendered in a menu layer below the header.
    - navigation.tabs.sticky # lock tabs below the header and always remain visible when scrolling down.
    - navigation.path # breadcrumb navigation is rendered above the title of each page ########### doesn't work!!!!
    - navigation.indexes # documents can be directly attached to sections.
    - navigation.top # A back-to-top button can be shown.
    - navigation.tracking # the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents.
    - navigation.prune # only the visible navigation items are included in the rendered HTML.
    - navigation.footer # "previous" and "next" buttons in the footer.
    - navigation.expand # the left sidebar will expand all collapsible subsections by default.
    # search
    - search.suggest # the search will display the likeliest completion for the last word which can be accepted.
    - search.highlight # highlight all occurrences after following the link.
    # content
    - content.action.edit # an "edit this page" button on the page.
    - content.action.view # a "view source" button on the page.
    - content.code.copy # copy-to-clipboard button on code blocks.
    # - content.tabs.link # all content tabs across the whole documentation site will be linked and switch to the same label when the user clicks on a tab.
    - toc.follow # the sidebar is automatically scrolled so that the active anchor is always visible.
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font: # can be set to any valid font from https://fonts.google.com/
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png
  language: en

  plugins:
    - search
    - search.suggest
    - search.highlight
    # - blog
    # - typeset
    - tags
    - i18n:
        docs_structure: suffix
        fallback_to_default: true
        reconfigure_material: true
        reconfigure_search: true
        languages:
          - locale: en
            default: true
            name: English
            build: true
          - locale: he
            name: hebrew
            build: true

  extra:
    # i18n_alternate: true
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Hebrew
        link: /he/
        lang: he
  #   social:
  #     - icon: fontawesome/brands/github
  #       link: https://github.com/Sh4peSh1fter

  # Extensions
markdown_extensions:
  - abbr # add a small tooltip to an element.
  - admonition # adds support for admonitions (call-outs).
  - attr_list # add HTML attributes and CSS classes to almost every Markdown inline.
  - def_list # add definition lists (description lists).
  - footnotes # define inline footnotes.
  - md_in_html # writing Markdown inside of HTML.
  - tables # create tables in Markdown.
  - toc: # automatically generates a table of contents from a document.
      title: Table of Contents
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex: # for rendering of block and inline block equations and integrates seamlessly with MathJax.
      generic: true
  - pymdownx.betterem: # detection of Markup to emphasize text in Markdown using special characters.
      smart_enable: all
  - pymdownx.caret # highlight text and define sub- and superscript.
  - pymdownx.details # making the resulting call-outs collapsible.
  - pymdownx.emoji: # automatically inlines bundled and custom icons and emojis.
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # syntax highlighting of inline code blocks.
  - pymdownx.keys # rendering of keyboard keys and combinations.
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols # converts some sequences of characters into their corresponding symbols.
  - pymdownx.snippets: # embed content from arbitrary files into a document.
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences: # arbitrary nesting of code and content blocks inside each other.
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # content tabs, a simple way to group related content and code blocks under accessible tabs.
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist: # usage of GitHub Flavored Markdown inspired task lists, following the same syntactical conventions.
      custom_checkbox: true
  - pymdownx.tilde
